//=========================================================
// src/InitDevice.c: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================

// USER INCLUDES
#include <SI_EFM8SB1_Register_Enums.h>
#include "InitDevice.h"

#include <compiler_defs.h>

#include <SI_EFM8SB1_Defs.h>
#include <SmaRTClock.h>

// USER PROTOTYPES
// USER FUNCTIONS


// $[Library Includes]
// [Library Includes]$
#define UART_ENABLE
//==============================================================================
// enter_DefaultMode_from_RESET
//==============================================================================
extern void enter_DefaultMode_from_RESET(void) {
	// $[Config Calls]
	// Save the SFRPAGE
	uint8_t SFRPAGE_save = SFRPAGE;
	PCA_0_enter_DefaultMode_from_RESET();
	VREG_0_enter_DefaultMode_from_RESET();
	PORTS_0_enter_DefaultMode_from_RESET();
	PORTS_1_enter_DefaultMode_from_RESET();
	PBCFG_0_enter_DefaultMode_from_RESET();
	RSTSRC_0_enter_DefaultMode_from_RESET();
	HFOSC_0_enter_DefaultMode_from_RESET();
	CLOCK_0_enter_DefaultMode_from_RESET();
	FLASH_0_enter_DefaultMode_from_RESET();
	TIMER01_0_enter_DefaultMode_from_RESET();
	TIMER16_2_enter_DefaultMode_from_RESET();
	TIMER_SETUP_0_enter_DefaultMode_from_RESET();
	ADC_0_enter_DefaultMode_from_RESET();
	UART_0_enter_DefaultMode_from_RESET();
    //XBR2 = 0x40; // Enable crossbar
	INTERRUPT_0_enter_DefaultMode_from_RESET();
	// Restore the SFRPAGE
	SFRPAGE = SFRPAGE_save;
	// [Config Calls]$


}


//================================================================================
// PCA_0_enter_DefaultMode_from_RESET
//================================================================================
extern void PCA_0_enter_DefaultMode_from_RESET(void) {
	// $[PCA0MD - PCA Mode]
	/*
	// WDTE (Watchdog Timer Enable) = DISABLED (Disable Watchdog Timer.)
	// CPS (PCA Counter/Timer Pulse Select) = SYSCLK_DIV_12 (System clock
	//     divided by 12.)
	// CIDL (PCA Counter/Timer Idle Control) = NORMAL (PCA continues to
	//     function normally while the system controller is in Idle Mode.)
	// ECF (PCA Counter/Timer Overflow Interrupt Enable) = OVF_INT_DISABLED
	//     (Disable the CF interrupt.)
	// WDTE (Watchdog Timer Enable) = DISABLED (Disable Watchdog Timer.)
	// WDLCK (Watchdog Timer Lock) = UNLOCKED (Watchdog Timer Enable
	//     unlocked.)
	*/
	SFRPAGE = 0x00;
	PCA0MD &= ~PCA0MD_WDTE__BMASK;
	PCA0MD = PCA0MD_CPS__SYSCLK_DIV_12 | PCA0MD_CIDL__NORMAL | PCA0MD_ECF__OVF_INT_DISABLED
		 | PCA0MD_WDTE__DISABLED | PCA0MD_WDLCK__UNLOCKED;
	// [PCA0MD - PCA Mode]$

	// $[PCA0H - PCA Counter/Timer High Byte]
	// [PCA0H - PCA Counter/Timer High Byte]$

	// $[PCA0L - PCA Counter/Timer Low Byte]
	// [PCA0L - PCA Counter/Timer Low Byte]$

	// $[PCA0PWM - PCA PWM Configuration]
	// [PCA0PWM - PCA PWM Configuration]$

	// $[PCA0CN0 - PCA Control 0]
	// [PCA0CN0 - PCA Control 0]$


}

//================================================================================
// VREG_0_enter_DefaultMode_from_RESET
//================================================================================
extern void VREG_0_enter_DefaultMode_from_RESET(void) {
	// $[REG0CN - Voltage Regulator Control]
	/*
	// OSCBIAS (High Frequency Oscillator Bias) = ENABLED (Enable the
	//     precision High Frequency Oscillator bias.)
	*/
	REG0CN = REG0CN_OSCBIAS__ENABLED;
	// [REG0CN - Voltage Regulator Control]$


}

//================================================================================
// PORTS_0_enter_DefaultMode_from_RESET
//================================================================================

extern void PORTS_0_enter_DefaultMode_from_RESET(void) {
	// $[P0 - Port 0 Pin Latch]
	// [P0 - Port 0 Pin Latch]$

	// $[P0MDOUT - Port 0 Output Mode]
	// [P0MDOUT - Port 0 Output Mode]$

	// $[P0MDIN - Port 0 Input Mode]
	// [P0MDIN - Port 0 Input Mode]$

	// $[P0SKIP - Port 0 Skip]
	// [P0SKIP - Port 0 Skip]$

	// $[P0MASK - Port 0 Mask]
	/*
	// B0 (Port 0 Bit 0 Mask Value) = IGNORED (P0.0 pin logic value is
	//     ignored and will not cause a port mismatch event.)
	// B1 (Port 0 Bit 1 Mask Value) = IGNORED (P0.1 pin logic value is
	//     ignored and will not cause a port mismatch event.)
	// B2 (Port 0 Bit 2 Mask Value) = COMPARED (P0.2 pin logic value is
	//     compared to P0MAT.2.)
	// B3 (Port 0 Bit 3 Mask Value) = IGNORED (P0.3 pin logic value is
	//     ignored and will not cause a port mismatch event.)
	// B4 (Port 0 Bit 4 Mask Value) = IGNORED (P0.4 pin logic value is
	//     ignored and will not cause a port mismatch event.)
	// B5 (Port 0 Bit 5 Mask Value) = IGNORED (P0.5 pin logic value is
	//     ignored and will not cause a port mismatch event.)
	// B6 (Port 0 Bit 6 Mask Value) = IGNORED (P0.6 pin logic value is
	//     ignored and will not cause a port mismatch event.)
	// B7 (Port 0 Bit 7 Mask Value) = IGNORED (P0.7 pin logic value is
	//     ignored and will not cause a port mismatch event.)
	*/
	/*P0MASK = P0MASK_B0__IGNORED | P0MASK_B1__IGNORED | P0MASK_B2__COMPARED
		 | P0MASK_B3__IGNORED | P0MASK_B4__IGNORED | P0MASK_B5__IGNORED
		 | P0MASK_B6__IGNORED | P0MASK_B7__IGNORED;*/
	// [P0MASK - Port 0 Mask]$

	// $[P0MAT - Port 0 Match]
	// [P0MAT - Port 0 Match]$

	// $[P0DRV - Port 0 Drive Strength]
	// [P0DRV - Port 0 Drive Strength]$
	//P0MDOUT =  P0MDOUT_B2__OPEN_DRAIN | P0MDOUT_B3__OPEN_DRAIN | P0MDOUT_B4__PUSH_PULL | P0MDOUT_B5__OPEN_DRAIN | P0MDOUT_B6__OPEN_DRAIN;
	P0MDOUT = P0MDOUT_B0__OPEN_DRAIN| P0MDOUT_B2__OPEN_DRAIN
		 | P0MDOUT_B3__OPEN_DRAIN | P0MDOUT_B4__OPEN_DRAIN | P0MDOUT_B5__OPEN_DRAIN;
		//P0MDIN = (P0MDIN&(~(P0MDIN_B0__BMASK|P0MDIN_B1__BMASK|P0MDIN_B7__BMASK))) | P0MDIN_B0__ANALOG | P0MDIN_B1__DIGITAL | P0MDIN_B7__DIGITAL;
	P0MDIN = P0MDIN_B0__DIGITAL | P0MDIN_B1__ANALOG | P0MDIN_B2__DIGITAL
		 | P0MDIN_B3__DIGITAL | P0MDIN_B4__DIGITAL | P0MDIN_B5__DIGITAL
		 | P0MDIN_B6__DIGITAL | P0MDIN_B7__ANALOG;
	P0SKIP = P0SKIP_B0__SKIPPED | P0SKIP_B1__NOT_SKIPPED | P0SKIP_B2__NOT_SKIPPED
		 | P0SKIP_B3__NOT_SKIPPED | P0SKIP_B4__NOT_SKIPPED | P0SKIP_B5__NOT_SKIPPED
		 | P0SKIP_B6__NOT_SKIPPED | P0SKIP_B7__NOT_SKIPPED;
	P0MASK = P0MASK_B0__IGNORED | P0MASK_B1__IGNORED | P0MASK_B2__IGNORED
		 | P0MASK_B3__IGNORED | P0MASK_B4__IGNORED | P0MASK_B5__IGNORED
		 | P0MASK_B6__COMPARED | P0MASK_B7__IGNORED;

}

//================================================================================
// PORTS_1_enter_DefaultMode_from_RESET
//================================================================================
extern void PORTS_1_enter_DefaultMode_from_RESET(void) {
	// $[P1 - Port 1 Pin Latch]
	// [P1 - Port 1 Pin Latch]$

	// $[P1MDOUT - Port 1 Output Mode]
	/*
	// B0 (Port 1 Bit 0 Output Mode) = OPEN_DRAIN (P1.0 output is open-
	//     drain.)
	// B1 (Port 1 Bit 1 Output Mode) = PUSH_PULL (P1.1 output is push-pull.)
	// B2 (Port 1 Bit 2 Output Mode) = OPEN_DRAIN (P1.2 output is open-
	//     drain.)
	// B3 (Port 1 Bit 3 Output Mode) = OPEN_DRAIN (P1.3 output is open-
	//     drain.)
	// B4 (Port 1 Bit 4 Output Mode) = OPEN_DRAIN (P1.4 output is open-
	//     drain.)
	// B5 (Port 1 Bit 5 Output Mode) = OPEN_DRAIN (P1.5 output is open-
	//     drain.)
	// B6 (Port 1 Bit 6 Output Mode) = OPEN_DRAIN (P1.6 output is open-
	//     drain.)
	// B7 (Port 1 Bit 7 Output Mode) = OPEN_DRAIN (P1.7 output is open-
	//     drain.)
	*/
	P1MDOUT = P1MDOUT_B0__PUSH_PULL | P1MDOUT_B1__PUSH_PULL | P1MDOUT_B2__PUSH_PULL
		 | P1MDOUT_B3__OPEN_DRAIN  | P1MDOUT_B5__OPEN_DRAIN
		 | P1MDOUT_B6__OPEN_DRAIN | P1MDOUT_B7__PUSH_PULL;
	// [P1MDOUT - Port 1 Output Mode]$

	// $[P1MDIN - Port 1 Input Mode]
	/*
	// B0 (Port 1 Bit 0 Input Mode) = DIGITAL (P1.0 pin is configured for
	//     digital mode.)
	// B1 (Port 1 Bit 1 Input Mode) = DIGITAL (P1.1 pin is configured for
	//     digital mode.)
	// B2 (Port 1 Bit 2 Input Mode) = DIGITAL (P1.2 pin is configured for
	//     digital mode.)
	// B3 (Port 1 Bit 3 Input Mode) = DIGITAL (P1.3 pin is configured for
	//     digital mode.)
	// B4 (Port 1 Bit 4 Input Mode) = DIGITAL (P1.4 pin is configured for
	//     digital mode.)
	// B5 (Port 1 Bit 5 Input Mode) = DIGITAL (P1.5 pin is configured for
	//     digital mode.)
	// B6 (Port 1 Bit 6 Input Mode) = ANALOG (P1.6 pin is configured for
	//     analog mode.)
	// B7 (Port 1 Bit 7 Input Mode) = ANALOG (P1.7 pin is configured for
	//     analog mode.)
	*/
	P1MDIN =  P1MDIN_B0__DIGITAL | P1MDIN_B1__DIGITAL | P1MDIN_B2__DIGITAL
		 | P1MDIN_B3__DIGITAL | P1MDIN_B4__ANALOG | P1MDIN_B5__DIGITAL
		 | P1MDIN_B6__DIGITAL | P1MDIN_B7__DIGITAL;
	// [P1MDIN - Port 1 Input Mode]$

	// $[P1SKIP - Port 1 Skip]
	// [P1SKIP - Port 1 Skip]$

	// $[P1MASK - Port 1 Mask]
	/*
	// B0 (Port 1 Bit 0 Mask Value) = IGNORED (P1.0 pin logic value is
	//     ignored and will not cause a port mismatch event.)
	// B1 (Port 1 Bit 1 Mask Value) = IGNORED (P1.1 pin logic value is
	//     ignored and will not cause a port mismatch event.)
	// B2 (Port 1 Bit 2 Mask Value) = COMPARED (P1.2 pin logic value is
	//     compared to P1MAT.2.)
	// B3 (Port 1 Bit 3 Mask Value) = IGNORED (P1.3 pin logic value is
	//     ignored and will not cause a port mismatch event.)
	// B4 (Port 1 Bit 4 Mask Value) = IGNORED (P1.4 pin logic value is
	//     ignored and will not cause a port mismatch event.)
	// B5 (Port 1 Bit 5 Mask Value) = IGNORED (P1.5 pin logic value is
	//     ignored and will not cause a port mismatch event.)
	// B6 (Port 1 Bit 6 Mask Value) = IGNORED (P1.6 pin logic value is
	//     ignored and will not cause a port mismatch event.)
	// B7 (Port 1 Bit 7 Mask Value) = IGNORED (P1.7 pin logic value is
	//     ignored and will not cause a port mismatch event.)
	*/
		P1SKIP = P1SKIP_B0__NOT_SKIPPED | P1SKIP_B1__NOT_SKIPPED | P1SKIP_B2__NOT_SKIPPED
		 | P1SKIP_B3__NOT_SKIPPED | P1SKIP_B4__SKIPPED | P1SKIP_B5__NOT_SKIPPED
		 | P1SKIP_B6__NOT_SKIPPED | P1SKIP_B7__NOT_SKIPPED;
	P1MASK = P1MASK_B0__IGNORED | P1MASK_B1__IGNORED | P1MASK_B2__IGNORED
		 | P1MASK_B3__COMPARED | P1MASK_B4__IGNORED | P1MASK_B5__IGNORED
		 | P1MASK_B6__IGNORED | P1MASK_B7__IGNORED;
	// [P1MASK - Port 1 Mask]$

	// $[P1MAT - Port 1 Match]
	// [P1MAT - Port 1 Match]$

	// $[P1DRV - Port 1 Drive Strength]
	// [P1DRV - Port 1 Drive Strength]$


}

//================================================================================
// PBCFG_0_enter_DefaultMode_from_RESET
//================================================================================
extern void PBCFG_0_enter_DefaultMode_from_RESET(void) {
	// $[XBR2 - Port I/O Crossbar 2]
	/*
	// WEAKPUD (Port I/O Weak Pullup Disable) = PULL_UPS_ENABLED (Weak
	//     Pullups enabled (except for Ports whose I/O are configured for analog
	//     mode).)
	// XBARE (Crossbar Enable) = ENABLED (Crossbar enabled.)
	*/
	XBR2 = XBR2_WEAKPUD__PULL_UPS_ENABLED | XBR2_XBARE__ENABLED;
	// [XBR2 - Port I/O Crossbar 2]$

	// $[XBR0 - Port I/O Crossbar 0]
	/*
	// URT0E (UART I/O Output Enable) = ENABLED (UART TX, RX routed to Port
	//     pins P0.4 and P0.5.)
	// SPI0E (SPI I/O Enable) = DISABLED (SPI I/O unavailable at Port pins.)
	// SMB0E (SMBus0 I/O Enable) = DISABLED (SMBus0 I/O unavailable at Port
	//     pins.)
	// CP0E (Comparator0 Output Enable) = DISABLED (CP0 unavailable at Port
	//     pin.)
	// CP0AE (Comparator0 Asynchronous Output Enable) = DISABLED
	//     (Asynchronous CP0 unavailable at Port pin.)
	// SYSCKE (SYSCLK Output Enable) = DISABLED (SYSCLK unavailable at Port
	//     pin.)
	*/
	XBR0 = XBR0_URT0E__ENABLED | XBR0_SPI0E__DISABLED | XBR0_SMB0E__DISABLED
		 | XBR0_CP0E__DISABLED | XBR0_CP0AE__DISABLED | XBR0_SYSCKE__DISABLED;
	// [XBR0 - Port I/O Crossbar 0]$

	// $[XBR1 - Port I/O Crossbar 1]
	// [XBR1 - Port I/O Crossbar 1]$


}


//================================================================================
// RSTSRC_0_enter_DefaultMode_from_RESET
//================================================================================
extern void RSTSRC_0_enter_DefaultMode_from_RESET(void) {
	// $[RSTSRC - Reset Source]
	/*
	// PORSF (Power-On / Supply Monitor Reset Flag, and Supply Monitor Reset
	//     Enable) = SET (A power-on or supply monitor reset occurred.)
	// MCDRSF (Missing Clock Detector Enable and Flag) = SET (A missing clock
	//     detector reset occurred.)
	// C0RSEF (Comparator0 Reset Enable and Flag) = NOT_SET (A Comparator 0
	//     reset did not occur.)
	// RTC0RE (RTC Reset Enable and Flag) = NOT_SET (A RTC alarm or
	//     oscillator fail reset did not occur.)
	*/


	RSTSRC = RSTSRC_PORSF__SET | RSTSRC_MCDRSF__SET | RSTSRC_C0RSEF__NOT_SET
		 | RSTSRC_RTC0RE__NOT_SET;
	// [RSTSRC - Reset Source]$


}

//================================================================================
// HFOSC_0_enter_DefaultMode_from_RESET
//================================================================================
extern void HFOSC_0_enter_DefaultMode_from_RESET(void) {
	// $[HFO#CAL - High Frequency Oscillator Calibration]
	// [HFO#CAL - High Frequency Oscillator Calibration]$

	// $[HFO#CN - High Frequency Oscillator Control]
	/*
	// IOSCEN (High Frequency Oscillator Enable) = ENABLED (High Frequency
	//     Oscillator enabled.)
	*/
	HFO0CN |= HFO0CN_IOSCEN__ENABLED;
	// [HFO#CN - High Frequency Oscillator Control]$

	// $[Oscillator Ready]
	while((HFO0CN & HFO0CN_IFRDY__BMASK) == HFO0CN_IFRDY__NOT_SET);
	// [Oscillator Ready]$


}

//================================================================================
// CLOCK_0_enter_DefaultMode_from_RESET
//================================================================================
extern void CLOCK_0_enter_DefaultMode_from_RESET(void) {
	// $[CLKSEL - Clock Select]
	/*
	// CLKDIV (Clock Source Divider) = SYSCLK_DIV_1 (SYSCLK is equal to
	//     selected clock source divided by 1.)
	// CLKSL (Clock Source Select) = HFOSC (Clock derived from the internal
	//     precision High-Frequency Oscillator.)
	*/
	CLKSEL = CLKSEL_CLKDIV__SYSCLK_DIV_1 | CLKSEL_CLKSL__HFOSC;
	// Wait for the clock to be ready
	while((CLKSEL & CLKSEL_CLKRDY__BMASK) != CLKSEL_CLKRDY__SET);
	// [CLKSEL - Clock Select]$


}

//================================================================================
// FLASH_0_enter_DefaultMode_from_RESET
//================================================================================
extern void FLASH_0_enter_DefaultMode_from_RESET(void) {
	// $[FLSCL - Flash Scale]
	/*
	// BYPASS (Flash Read Timing One-Shot Bypass) = SYSCLK (The system clock
	//     determines the flash read time. This setting should be used for
	//     frequencies greater than 14 MHz.)
	*/
	//FLSCL = FLSCL_BYPASS__SYSCLK;
	// [FLSCL - Flash Scale]$


}

//================================================================================
// TIMER01_0_enter_DefaultMode_from_RESET
//================================================================================

extern void TIMER01_0_enter_DefaultMode_from_RESET(void) {
	// $[Timer Initialization]
	//Save Timer Configuration
	uint8_t TCON_save = TCON;
	//Stop Timers
	TCON &= TCON_TR0__BMASK & TCON_TR1__BMASK;

	// [Timer Initialization]$

	// $[TH0 - Timer 0 High Byte]
	// [TH0 - Timer 0 High Byte]$

	// $[TL0 - Timer 0 Low Byte]
	// [TL0 - Timer 0 Low Byte]$

	// $[TH1 - Timer 1 High Byte]
	/*
	// TH1 (Timer 1 High Byte) = 0x96
	*/
	//TH1 = 96;//43;//TH1 = (0x96 << TH1_TH1__SHIFT);

	TH1 = 43;     //43-57600
	TL1 = (0xCB << TL1_TL1__SHIFT);
	TCON = TCON_save;
	//TMOD &= 0xCF;
	//TMOD |= 0x20;
	//TH1 = 149;
	//TL1 = 170;
	//TCON = TCON_save;
	// [Timer Restoration]$


}

//================================================================================
// TIMER16_2_enter_DefaultMode_from_RESET
//================================================================================
extern void TIMER16_2_enter_DefaultMode_from_RESET(void) {
	// $[Timer Initialization]
	// Save Timer Configuration
	uint8_t TMR2CN0_TR2_save = TMR2CN0 & TMR2CN0_TR2__BMASK;
	// Stop Timer
	TMR2CN0 &= ~(TMR2CN0_TR2__BMASK);
	// [Timer Initialization]$

	// $[TMR2CN0 - Timer 2 Control]
	// [TMR2CN0 - Timer 2 Control]$

	// $[TMR2H - Timer 2 High Byte]
	/*
	// TMR2H (Timer 2 High Byte) = 0xB0
	*/
	TMR2H = (0xB0 << TMR2H_TMR2H__SHIFT);
	// [TMR2H - Timer 2 High Byte]$

	// $[TMR2L - Timer 2 Low Byte]
	/*
	// TMR2L (Timer 2 Low Byte) = 0x3F
	*/
	TMR2L = (0x3F << TMR2L_TMR2L__SHIFT);
	// [TMR2L - Timer 2 Low Byte]$

	// $[TMR2RLH - Timer 2 Reload High Byte]
	/*
	// TMR2RLH (Timer 2 Reload High Byte) = 0xB0
	*/
	TMR2RLH = (0xB0 << TMR2RLH_TMR2RLH__SHIFT);
	// [TMR2RLH - Timer 2 Reload High Byte]$

	// $[TMR2RLL - Timer 2 Reload Low Byte]
	/*
	// TMR2RLL (Timer 2 Reload Low Byte) = 0x3F
	*/
	TMR2RLL = (0x3F << TMR2RLL_TMR2RLL__SHIFT);
	// [TMR2RLL - Timer 2 Reload Low Byte]$

	// $[TMR2CN0]
	/*
	// TR2 (Timer 2 Run Control) = RUN (Start Timer 2 running.)
	*/
	TMR2CN0 |= TMR2CN0_TR2__RUN;
	// [TMR2CN0]$

	// $[Timer Restoration]
	// Restore Timer Configuration
	TMR2CN0 |= TMR2CN0_TR2_save;
	// [Timer Restoration]$


}



extern void TIMER_SETUP_0_enter_DefaultMode_from_RESET(void) {
	// $[CKCON0 - Clock Control 0]
	/*
	// SCA (Timer 0/1 Prescale) = SYSCLK_DIV_12 (System clock divided by 12.)
	// T0M (Timer 0 Clock Select) = PRESCALE (Counter/Timer 0 uses the clock
	//     defined by the prescale field, SCA.)
	// T2MH (Timer 2 High Byte Clock Select) = EXTERNAL_CLOCK (Timer 2 high
	//     byte uses the clock defined by T2XCLK in TMR2CN0.)
	// T2ML (Timer 2 Low Byte Clock Select) = EXTERNAL_CLOCK (Timer 2 low
	//     byte uses the clock defined by T2XCLK in TMR2CN0.)
	// T3MH (Timer 3 High Byte Clock Select) = EXTERNAL_CLOCK (Timer 3 high
	//     byte uses the clock defined by T3XCLK in TMR3CN0.)
	// T3ML (Timer 3 Low Byte Clock Select) = EXTERNAL_CLOCK (Timer 3 low
	//     byte uses the clock defined by T3XCLK in TMR3CN0.)
	// T1M (Timer 1 Clock Select) = SYSCLK (Timer 1 uses the system clock.)
	*/
	CKCON0 = CKCON0_SCA__SYSCLK_DIV_12 | CKCON0_T0M__PRESCALE | CKCON0_T2MH__EXTERNAL_CLOCK
		 | CKCON0_T2ML__EXTERNAL_CLOCK | CKCON0_T3MH__EXTERNAL_CLOCK | CKCON0_T3ML__EXTERNAL_CLOCK
		 | CKCON0_T1M__SYSCLK;
	// [CKCON0 - Clock Control 0]$

	// $[TMOD - Timer 0/1 Mode]
	/*
	// T0M (Timer 0 Mode Select) = MODE0 (Mode 0, 13-bit Counter/Timer)
	// T1M (Timer 1 Mode Select) = MODE2 (Mode 2, 8-bit Counter/Timer with
	//     Auto-Reload)
	// CT0 (Counter/Timer 0 Select) = TIMER (Timer Mode. Timer 0 increments
	//     on the clock defined by T0M in the CKCON register.)
	// GATE0 (Timer 0 Gate Control) = DISABLED (Timer 0 enabled when TR0 = 1
	//     irrespective of INT0 logic level.)
	// CT1 (Counter/Timer 1 Select) = TIMER (Timer Mode. Timer 1 increments
	//     on the clock defined by T1M in the CKCON register.)
	// GATE1 (Timer 1 Gate Control) = DISABLED (Timer 1 enabled when TR1 = 1
	//     irrespective of INT1 logic level.)
	*/
	TMOD = TMOD_T0M__MODE0 | TMOD_T1M__MODE2 | TMOD_CT0__TIMER | TMOD_GATE0__DISABLED
		 | TMOD_CT1__TIMER | TMOD_GATE1__DISABLED;
	// [TMOD - Timer 0/1 Mode]$

	// $[TCON - Timer 0/1 Control]
	/*
	// TR1 (Timer 1 Run Control) = RUN (Start Timer 1 running.)
	*/
	TCON |= TCON_TR1__RUN;
	// [TCON - Timer 0/1 Control]$


}

//================================================================================
// ADC_0_enter_DefaultMode_from_RESET
//================================================================================
extern void ADC_0_enter_DefaultMode_from_RESET(void) {
	// $[ADC0MX - ADC0 Multiplexer Selection]
	/*
	// ADC0MX (AMUX0 Positive Input Selection) = ADC0P12 (Select channel
	//     ADC0.12.)
	*/
	ADC0MX = ADC0MX_ADC0MX__ADC0P12;
	// [ADC0MX - ADC0 Multiplexer Selection]$

	// $[ADC0AC - ADC0 Accumulator Configuration]
	/*
	// ADRPT (Repeat Count) = ACC_4 (Perform and Accumulate 4 conversions (1
	//     conversion in 12-bit mode).)
	// AD12BE (12-Bit Mode Enable) = 12_BIT_ENABLED (Enable 12-bit mode.)
	// ADAE (Accumulate Enable) = ACC_DISABLED (ADC0H:ADC0L contain the
	//     result of the latest conversion when Burst Mode is disabled.)
	// ADSJST (Accumulator Shift and Justify) = RIGHT_NO_SHIFT (Right
	//     justified. No shifting applied.)
	*/
	ADC0AC = ADC0AC_ADRPT__ACC_4 | ADC0AC_AD12BE__12_BIT_ENABLED | ADC0AC_ADAE__ACC_DISABLED
		 | ADC0AC_ADSJST__RIGHT_NO_SHIFT;
	// [ADC0AC - ADC0 Accumulator Configuration]$

	// $[ADC0TK - ADC0 Burst Mode Track Time]
	// [ADC0TK - ADC0 Burst Mode Track Time]$

	// $[ADC0PWR - ADC0 Power Control]
	// [ADC0PWR - ADC0 Power Control]$

	// $[ADC0CF - ADC0 Configuration]
	/*
	// AD8BE (8-Bit Mode Enable) = NORMAL (ADC0 operates in 10-bit or 12-bit
	//     mode (normal operation).)
	// ADGN (Gain Control) = GAIN_0P5 (The on-chip PGA gain is 0.5.)
	// ADSC (SAR Clock Divider) = 0x02
	// ADTM (Track Mode) = TRACK_NORMAL (Normal Track Mode. When ADC0 is
	//     enabled, conversion begins immediately following the start-of-
	//     conversion signal.)
	*/
	ADC0CF = ADC0CF_AD8BE__NORMAL | ADC0CF_ADGN__GAIN_0P5 | (0x02 << ADC0CF_ADSC__SHIFT)
		 | ADC0CF_ADTM__TRACK_NORMAL;
	// [ADC0CF - ADC0 Configuration]$

	// $[ADC0GTH - ADC0 Greater-Than High Byte]
	/*
	// ADC0GTH (Greater-Than High Byte) = 0x00
	*/
	ADC0GTH = (0x00 << ADC0GTH_ADC0GTH__SHIFT);
	// [ADC0GTH - ADC0 Greater-Than High Byte]$

	// $[ADC0GTL - ADC0 Greater-Than Low Byte]
	/*
	// ADC0GTL (Greater-Than Low Byte) = 0x00
	*/
	ADC0GTL = (0x00 << ADC0GTL_ADC0GTL__SHIFT);
	// [ADC0GTL - ADC0 Greater-Than Low Byte]$

	// $[ADC0LTH - ADC0 Less-Than High Byte]
	// [ADC0LTH - ADC0 Less-Than High Byte]$

	// $[ADC0LTL - ADC0 Less-Than Low Byte]
	// [ADC0LTL - ADC0 Less-Than Low Byte]$

	// $[ADC0CN0 - ADC0 Control 0]
	/*
	// ADBMEN (Burst Mode Enable) = BURST_ENABLED (Enable ADC0 burst mode.)
	// ADCM (Start of Conversion Mode Select) = TIMER2 (ADC0 conversion
	//     initiated on overflow of Timer 2.)
	*/
	ADC0CN0 &= ~ADC0CN0_ADCM__FMASK;
	ADC0CN0 |= ADC0CN0_ADBMEN__BURST_ENABLED
		 | ADC0CN0_ADCM__TIMER2;
	// [ADC0CN0 - ADC0 Control 0]$


}


//int adc_busy = 0;

/*extern int enable_adc(int adc) {
	if (adc_busy ||
			(ADC_CHANNEL_ID != adc && ADC_CHANNEL_VBAT != adc)) {
		return -1;
	}
	if (adc == ADC_CHANNEL_ID) {
	     ADC0MX = ADC0MX_ADC0MX__ADC0P1;
	} else if (adc == ADC_CHANNEL_VBAT) {
	     ADC0MX = ADC0MX_ADC0MX__ADC0P7;
	}
	kick_adc();
	adc_busy = 1;
	return 0;
}*/





//================================================================================
// UART_0_enter_DefaultMode_from_RESET
//================================================================================
extern void UART_0_enter_DefaultMode_from_RESET(void) {
	// $[SCON0 - UART0 Serial Port Control]
	/*
	// REN (Receive Enable) = RECEIVE_ENABLED (UART0 reception enabled.)
	*/
	//SCON0 |= SCON0_REN__RECEIVE_ENABLED;
	// [SCON0 - UART0 Serial Port Control]$
#ifdef UART_ENABLE
     SCON0 |= SCON0_REN__RECEIVE_ENABLED; // SCON0: 8-bit variable bit rate
#endif
	 //        level of STOP bit is ignored
	     //        RX enabled
	     //        ninth bits are zeros
	     //        clear RI0 and TI0 bits
	     /*
	     if (SYSCLK / BAUDRATE / 2 / 256 < 1)
	     {
	         TH1 = -(SYSCLK / BAUDRATE / 2); // 0x96
	         CKCON &= ~0x0B; // T1M = 1; SCA1:0 = xx
	         CKCON |= 0x08;
	     }
	     else if (SYSCLK / BAUDRATE / 2 / 256 < 4)
	     {
	         TH1 = -(SYSCLK / BAUDRATE / 2 / 4);
	         CKCON &= ~0x0B; // T1M = 0; SCA1:0 = 01
	         CKCON |= 0x01;
	     }
	     else if (SYSCLK / BAUDRATE / 2 / 256 < 12)
	     {
	         TH1 = -(SYSCLK / BAUDRATE / 2 / 12);
	         CKCON &= ~0x0B; // T1M = 0; SCA1:0 = 00
	     }
	     else
	     {
	         TH1 = -(SYSCLK / BAUDRATE / 2 / 48);
	         CKCON &= ~0x0B; // T1M = 0; SCA1:0 = 10
	         CKCON |= 0x02;
	     }

	     TL1 = TH1; // init Timer1
	     TMOD &= ~0xf0; // TMOD: timer 1 in 8-bit autoreload
	     TMOD |= 0x20;
	     TR1 = 1; // START Timer1
	     */
}

extern void UART_0_enter_DefaultMode_to_Normal(void) {

	// SCON0 &= ~SCON0_REN__RECEIVE_ENABLED; // SCON0: 8-bit variable bit rate
	 XBR0 &= ~XBR0_URT0E__ENABLED;
}

extern void UART_0_enter_DefaultMode_to_Uart(void) {

#ifdef UART_ENABLE
	// SCON0 &= ~SCON0_REN__RECEIVE_ENABLED; // SCON0: 8-bit variable bit rate
	 XBR0 |= XBR0_URT0E__ENABLED;
#endif
}

//================================================================================
// INTERRUPT_0_enter_DefaultMode_from_RESET
//================================================================================
extern void INTERRUPT_0_enter_DefaultMode_from_RESET(void) {
	// $[EIE1 - Extended Interrupt Enable 1]
	/*
	// EADC0 (ADC0 Conversion Complete Interrupt Enable) = ENABLED (Enable
	//     interrupt requests generated by the ADINT flag.)
	// ECP0 (Comparator0 (CP0) Interrupt Enable) = DISABLED (Disable CP0
	//     interrupts.)
	// EPCA0 (Programmable Counter Array (PCA0) Interrupt Enable) = DISABLED
	//     (Disable all PCA0 interrupts.)
	// ERTC0A (RTC Alarm Interrupt Enable) = DISABLED (Disable RTC Alarm
	//     interrupts.)
	// ESMB0 (SMBus (SMB0) Interrupt Enable) = DISABLED (Disable all SMB0
	//     interrupts.)
	// ET3 (Timer 3 Interrupt Enable) = DISABLED (Disable Timer 3
	//     interrupts.)
	// EWADC0 (Window Comparison ADC0 Interrupt Enable) = DISABLED (Disable
	//     ADC0 Window Comparison interrupt.)
	*/
	EIE1 = EIE1_EADC0__ENABLED | EIE1_ECP0__DISABLED | EIE1_EPCA0__DISABLED
		 | EIE1_ERTC0A__DISABLED | EIE1_ESMB0__DISABLED | EIE1_ET3__DISABLED
		 | EIE1_EWADC0__DISABLED;
	// [EIE1 - Extended Interrupt Enable 1]$

	// $[EIP1 - Extended Interrupt Priority 1]
	// [EIP1 - Extended Interrupt Priority 1]$

	// $[IE - Interrupt Enable]
	/*
	// EA (All Interrupts Enable) = ENABLED (Enable each interrupt according
	//     to its individual mask setting.)
	// EX0 (External Interrupt 0 Enable) = DISABLED (Disable external
	//     interrupt 0.)
	// EX1 (External Interrupt 1 Enable) = DISABLED (Disable external
	//     interrupt 1.)
	// ESPI0 (SPI0 Interrupt Enable) = DISABLED (Disable all SPI0
	//     interrupts.)
	// ET0 (Timer 0 Interrupt Enable) = DISABLED (Disable all Timer 0
	//     interrupt.)
	// ET1 (Timer 1 Interrupt Enable) = DISABLED (Disable all Timer 1
	//     interrupt.)
	// ET2 (Timer 2 Interrupt Enable) = DISABLED (Disable Timer 2 interrupt.)
	// ES0 (UART0 Interrupt Enable) = DISABLED (Disable UART0 interrupt.)
	*/
	IE = IE_EA__ENABLED | IE_EX0__DISABLED | IE_EX1__DISABLED | IE_ESPI0__DISABLED
	//	 | IE_ET0__DISABLED | IE_ET1__DISABLED | IE_ET2__DISABLED | IE_ES0__DISABLED;
			| IE_ET0__DISABLED | IE_ET1__DISABLED | IE_ET2__ENABLED | IE_ES0__DISABLED;
	// [IE - Interrupt Enable]$

	// $[IP - Interrupt Priority]
	// [IP - Interrupt Priority]$

	// $[EIE2 - Extended Interrupt Enable 2]
	// [EIE2 - Extended Interrupt Enable 2]$

	// $[EIP2 - Extended Interrupt Priority 2]
	// [EIP2 - Extended Interrupt Priority 2]$


}

#define TI0 SCON0_TI
#define RI0 SCON0_RI
#define CKCON CKCON0
#define BAUDRATE 115200

//-----------------------------------------------------------------------------
// Interrupt Service Routines
//-----------------------------------------------------------------------------

//  uart send, count max number is 255, limited by XRAM size
extern void msleep(int ms);
void uart_send(char *buf, int count)
{
#ifdef UART_ENABLE
	char *ptr = buf;
	do{
	    SBUF0 = *ptr++;
	   // msleep(1000);
		while(TI0 == 0);
		TI0 = 0;
	}while(--count);
#endif
}

// uart receive, count max 512, limited by XRAM size
void uart_receive(char *buf, int count_uart)
{
	char* ptr = buf;
	do{
		if(RI0 == 1)
		{
			*ptr++ = SBUF0;
			RI0 = 0;
			count_uart--;
		}
	}while(count_uart);
}
int uart_receive_timeout(char *buf, int count_uart,int timeout_ms)
{
	int time=0;
	char* ptr = buf;
	do{
		if(RI0 == 1)
		{
			*ptr++ = SBUF0;
			RI0 = 0;
			count_uart--;
		}
		if((count_uart)&&(time>=timeout_ms))//timeout
			return 0;
		msleep(1);
		time++;
	}while(count_uart);
	return 1;
}
int uart_receive_have_timeout(long timeout_ms)//受到干扰，读不到正确的串口输入   be disturbed，cannot recv right uart string
{
	char buf[8]={'1','2','3','4','5','6','7','8'};
	int count_uart=8;
	long time=0;
	char* ptr = buf;

	while(time<=timeout_ms){
		if(RI0!=1)
			time++;
		else
			break;
	}
	if(RI0!=1){
		return 0;
	}
	else{
		*ptr++ = SBUF0;
		RI0= 0;
		count_uart--;
		if(buf[0]=='d'){
			do{
				if(RI0 == 1)
				{
					*ptr++ = SBUF0;
					RI0 = 0;
					count_uart--;
				}
			}while(count_uart);
			if((buf[0]=='d')&&(buf[1]=='i')&&(buf[2]=='s')&&(buf[3]=='t')&&(buf[4]=='e')&&(buf[5]=='n')&&(buf[6]=='c')&&(buf[7]=='e')){
				while(RI0==1)//该循环清空这次接受到的所有字节
				{
					buf[0]=SBUF0;
					RI0=0;
				}
				return 1;
			}
			else{
				uart_send(buf, sizeof(buf));
				while(RI0==1)//该循环清空这次接受到的所有字节
				{
					buf[0]=SBUF0;
					RI0=0;
				}
				return 0;
			}
		}
		else{
			while(RI0==1)//该循环清空这次接受到的所有字节
			{
				buf[0]=SBUF0;
				RI0=0;
			}
			return 0;
		}
	}
	/*char buf[8]={'1','2','3','4','5','6','7','8'};
	int count_uart=8;
	int time=0;
	char* ptr = buf;
	do{
		if(RI0 == 1)
		{
			*ptr++ = SBUF0;
			RI0 = 0;
			count_uart--;
		}
		if((count_uart)&&(time>=timeout_ms)){//timeout
			uart_send(buf, sizeof(buf));
			while(RI0==1)//该循环清空这次接受到的所有字节
			{
				buf[0]=SBUF0;
				RI0=0;
			}
			return 0;
		}
		if(count_uart==8)
			msleep(1);
		time++;
	}while(count_uart);
	if((buf[0]=='d')&&(buf[1]=='i')&&(buf[2]=='s')&&(buf[3]=='t')&&(buf[4]=='e')&&(buf[5]=='n')&&(buf[6]=='c')&&(buf[7]=='e')){
		return 1;
	}
	else{
		uart_send(buf, sizeof(buf));
		while(RI0==1)//该循环清空这次接受到的所有字节
		{
			buf[0]=SBUF0;
			RI0=0;
		}
		return 0;
	}*/
/*
	if(uart_receive_timeout(buf,count_uart,time_ms)){
		if((buf[0]=='d')&&(buf[1]=='i')&&(buf[2]=='s')&&(buf[3]=='t')&&(buf[4]=='e')&&(buf[5]=='n')&&(buf[6]=='c')&&(buf[7]=='e')){
				return 1;
		}else{
			uart_send(buf, sizeof(buf));
			while(RI0==1)//该循环清空这次接受到的所有字节
			{
				buf[0]=SBUF0;
				RI0=0;
			}
			return 0;
		}
	}
	else{
		return 0;
	}
*/
}
int uart_receive_no_timeout()
{
	char buf[8];
	char* ptr = buf;
	int count_uart=8;
	int i=0;
	do{
		if(RI0 == 1)
		{
			*ptr++ = SBUF0;
			RI0 = 0;
			count_uart--;
		}
	}while(count_uart);
	if((buf[0]=='d')&&(buf[1]=='i')&&(buf[2]=='s')&&(buf[3]=='t')&&(buf[4]=='e')&&(buf[5]=='n')&&(buf[6]=='c')&&(buf[7]=='e')){
		return 1;
	}
	else{
		uart_send(buf, sizeof(buf));
		while(RI0==1)//该循环清空这次接受到的所有字节
		{
			buf[0]=SBUF0;
			RI0=0;
		}
		return 0;
	}
}
/*void uart_receive_phone()
{
	char buf[8];
	char* ptr = buf;
	int count_uart=8;
	do{
		if(RI0 == 1)
		{
			*ptr++ = SBUF0;
			RI0 = 0;
			count_uart--;
		}
	}while(count_uart);
	if((buf[0]=='d')&&(buf[1]=='i')&&(buf[2]=='s')&&(buf[3]=='t')&&(buf[4]=='e')&&(buf[5]=='n')&&(buf[6]=='c')&&(buf[7]=='e')){
		uart_send("ok", sizeof( "ok"));
		uart_send("\r\n", sizeof( "\r\n"));
	}
}*/
/*int uart_receive_test()
{
	char* ptr;
	int j=0;
	uart_send("f", sizeof( "f"));
	do{
		j++;
		if(RI0 == 1)
		{
			*ptr++ = SBUF0;
			RI0 = 0;
			return 1;
		}
	//}while((count_uart)&&(j<3000));
	}while((j<10000));
	return 0;
}*/
